### ISSUE TITLE
stort problem...

### ISSUE THREAD

**Issue by WhoTookTotto** [BonelessBob/Makerspace#1]
alt, bare alt, ikke noe bra her. start igjen 2-

**Comment by BonelessBob-zz** [comment]
Ok i have forwarded your error to HR, they will look into it

**Comment by BonelessBob** [comment]
After our board meeting HR has decidedthat no one gives a shit

**Comment by BonelessBob-zz** [comment]
After our board meeting HR has decidedthat no one gives a shit
